"""added routing table

Revision ID: 65b638f038d8
Revises: 
Create Date: 2025-06-21 11:11:38.156103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b638f038d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('routed_to', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('documents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.alter_column('logs', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_constraint(op.f('logs_document_id_fkey'), 'logs', type_='foreignkey')
    op.drop_constraint(op.f('logs_user_id_fkey'), 'logs', type_='foreignkey')
    op.create_foreign_key(None, 'logs', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.create_foreign_key(op.f('logs_user_id_fkey'), 'logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('logs_document_id_fkey'), 'logs', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.alter_column('logs', 'event_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_table('routing')
    # ### end Alembic commands ###
